<?php

namespace AppBundle\Repository;

/**
 * ProfilpicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilpicRepository extends \Doctrine\ORM\EntityRepository
{
}
