rythm:
    resource: "@RythmBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

accueil:
    path:   /index
    defaults: { _controller: AppBundle:Accueil:accueil}

profil:
    path:   /profil
    defaults: { _controller: AppBundle:Profil:profil}

user_profil:
    path:   /user/profil/{username}
    defaults: { _controller: AppBundle:Profil:user}

user_ami:
    path:   /user/profil/ami/{username}
    defaults: { _controller: AppBundle:Profil:ami}

profil_modif:
    path:   /profil/modif
    defaults: { _controller: AppBundle:Usermodif:profilmodif}

new_album:
    path:   /album/new
    defaults: { _controller: RythmBundle:Album:new}

list_album:
    path:   /album/list
    defaults: { _controller: RythmBundle:Album:list}

page_album:
    path:   /album/{titre}
    defaults: { _controller: RythmBundle:Album:page}

new_musique:
    path:   /album/musique/{idalbum}
    defaults: { _controller: RythmBundle:Album:musique}

search:
    path: /search
    defaults: { _controller: AppBundle:Search:album}